dist: trusty
sudo: false

language: elixir
otp_release:
  - 19.3
elixir:
  - 1.4.2

cache:
  directories:
    - _build
    - deps

addons:
  postgresql: "9.6"

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix do deps.get, compile
before_script:
  - cd apps/ryal_core && mix db.reset && cd ../..
script:
  - mix coveralls.travis
